version = 1

test_patterns = [
    "/tests/e2e/specs/**",
    "/tests/unit/**/*"
]

exclude_patterns = [
    "/dist",
    "/cypress",
    "/.github"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
  environment = ["browser", "jest"]

[[transformers]]
name = "prettier"
enabled = true
